sudo: true # required for Docker
dist: xenial

language: node

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234


install: skip

script: TRAVIS_TAG=latest bash ./build-tools/build-push-docker.sh

deploy:
  provider: script
  script: bash ./build-tools/build-push-docker.sh
  skip_cleanup: true
  on:
    tags: true
